// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// tree_fit
arma::mat tree_fit(const arma::colvec& obs, const arma::colvec& dimension_vec, const arma::colvec& hyper, const int& step);
RcppExport SEXP _WARP_tree_fit(SEXP obsSEXP, SEXP dimension_vecSEXP, SEXP hyperSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::colvec& >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type dimension_vec(dimension_vecSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type hyper(hyperSEXP);
    Rcpp::traits::input_parameter< const int& >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_fit(obs, dimension_vec, hyper, step));
    return rcpp_result_gen;
END_RCPP
}
// tree_likelihood
arma::vec tree_likelihood(arma::vec const& obs, arma::vec const& dimension_vec, arma::mat const& hyper_grid);
RcppExport SEXP _WARP_tree_likelihood(SEXP obsSEXP, SEXP dimension_vecSEXP, SEXP hyper_gridSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec const& >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< arma::vec const& >::type dimension_vec(dimension_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat const& >::type hyper_grid(hyper_gridSEXP);
    rcpp_result_gen = Rcpp::wrap(tree_likelihood(obs, dimension_vec, hyper_grid));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WARP_tree_fit", (DL_FUNC) &_WARP_tree_fit, 4},
    {"_WARP_tree_likelihood", (DL_FUNC) &_WARP_tree_likelihood, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_WARP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
