# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tree_fit <- function(obs, dimension_vec, hyper, step) {
    .Call('_WARP_tree_fit', PACKAGE = 'WARP', obs, dimension_vec, hyper, step)
}

tree_likelihood <- function(obs, dimension_vec, hyper_grid) {
    .Call('_WARP_tree_likelihood', PACKAGE = 'WARP', obs, dimension_vec, hyper_grid)
}

